sequenceDiagram
  participant participant_assertHexColor as assertHexColor
  participant participant_isHexColor as isHexColor
  participant_assertHexColor->>participant_isHexColor: isHexColor()
  participant_isHexColor-->>participant_assertHexColor: return
