sequenceDiagram
  participant participant_createRoleRecord as createRoleRecord
  participant participant_createSemanticStatusSwatches as createSemanticStatusSwatches
  participant_createSemanticStatusSwatches->>participant_createRoleRecord: createRoleRecord()
  participant_createRoleRecord-->>participant_createSemanticStatusSwatches: return
