sequenceDiagram
  participant participant_parseHexColor as parseHexColor
  participant participant_parseHexColorOrThrow as parseHexColorOrThrow
  participant_parseHexColorOrThrow->>participant_parseHexColor: parseHexColor()
  participant_parseHexColor-->>participant_parseHexColorOrThrow: return
