sequenceDiagram
participant participant_src_contrast_ts as src/contrast.ts
participant participant_src_culori_fn_ts as src/culori-fn.ts
participant participant_src_culori_ts as src/culori.ts
participant participant_src_harmony_ts as src/harmony.ts
participant participant_src_hex_ts as src/hex.ts
participant participant_src_index_ts as src/index.ts
participant participant_src_internal_culori_ts as src/internal-culori.ts
participant participant_src_neutral_ts as src/neutral.ts
participant participant_src_semantic_status_ts as src/semantic-status.ts
participant participant_src_semantics_ts as src/semantics.ts
participant participant_src_swatches_ts as src/swatches.ts
participant participant_src_theme_colors_ts as src/theme-colors.ts
  participant_src_contrast_ts->>participant_src_hex_ts: imports
  participant_src_contrast_ts->>participant_src_internal_culori_ts: imports
  participant_src_harmony_ts->>participant_src_hex_ts: imports
  participant_src_harmony_ts->>participant_src_internal_culori_ts: imports
  participant_src_internal_culori_ts->>participant_src_hex_ts: imports
  participant_src_neutral_ts->>participant_src_harmony_ts: imports
  participant_src_neutral_ts->>participant_src_hex_ts: imports
  participant_src_neutral_ts->>participant_src_internal_culori_ts: imports
  participant_src_neutral_ts->>participant_src_swatches_ts: imports
  participant_src_semantic_status_ts->>participant_src_hex_ts: imports
  participant_src_semantic_status_ts->>participant_src_swatches_ts: imports
  participant_src_semantics_ts->>participant_src_harmony_ts: imports
  participant_src_semantics_ts->>participant_src_swatches_ts: imports
  participant_src_swatches_ts->>participant_src_hex_ts: imports
  participant_src_swatches_ts->>participant_src_internal_culori_ts: imports
  participant_src_theme_colors_ts->>participant_src_harmony_ts: imports
  participant_src_theme_colors_ts->>participant_src_hex_ts: imports
  participant_src_theme_colors_ts->>participant_src_neutral_ts: imports
  participant_src_theme_colors_ts->>participant_src_swatches_ts: imports
